//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoSoTuChonBenTre
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoGenerateCode
    {
        public System.Guid Id { get; set; }
        public string TableName { get; set; }
        public int Value { get; set; }
        public string TablePattern { get; set; }
    }
}
