//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoSoTuChonBenTre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dai
    {
        public int IDDai { get; set; }
        public string MaDai { get; set; }
        public string TenDai { get; set; }
        public Nullable<int> Mien { get; set; }
        public string Thu { get; set; }
    }
}
