//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoSoTuChonBenTre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int IDGame { get; set; }
        public Nullable<int> NgayChoi { get; set; }
        public string MaDai { get; set; }
        public string Lo { get; set; }
        public string So { get; set; }
        public Nullable<double> SoTien { get; set; }
        public int IDTaiKhoan { get; set; }
        public Nullable<bool> XacNhan { get; set; }
        public string ThoiGianDat { get; set; }
        public Nullable<int> Loai { get; set; }
    
        public virtual TaiKhoanHeThong TaiKhoanHeThong { get; set; }
    }
}
