//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoSoTuChonBenTre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lo
    {
        public int IDLo { get; set; }
        public string MaLo { get; set; }
        public string TenLo { get; set; }
        public Nullable<int> Loai { get; set; }
    }
}
