//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoSoTuChonBenTre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int menu_id { get; set; }
        public string menu_title { get; set; }
        public string menu_description { get; set; }
        public string menu_url { get; set; }
        public string menu_valuepath { get; set; }
        public Nullable<int> menu_parent_id { get; set; }
        public string menu_order { get; set; }
    }
}
