//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoSoTuChonBenTre
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoXoTuChon_BenTreEntities : DbContext
    {
        public SoXoTuChon_BenTreEntities()
            : base("name=SoXoTuChon_BenTreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dai> Dais { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Lo> Loes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<PhieuDuThuong> PhieuDuThuongs { get; set; }
        public virtual DbSet<AutoGenerateCode> AutoGenerateCodes { get; set; }
        public virtual DbSet<TaiKhoanHeThong> TaiKhoanHeThongs { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<NapTien> NapTien { get; set; }
        public virtual DbSet<RutTien> RutTien { get; set; }
        public virtual DbSet<TraThuong> TraThuong { get; set; }
    }
}
