//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoSoTuChonBenTre
{
    using System;
    using System.Collections.Generic;
    
    public partial class NapTien
    {
        public int IDNap { get; set; }
        public Nullable<int> NgayNap { get; set; }
        public int IDTaiKhoanNap { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string NganHang { get; set; }
        public Nullable<bool> XacNhan { get; set; }
        public Nullable<int> IDTaiKhoanXacNhan { get; set; }
        public Nullable<int> NgayXacNhan { get; set; }
        public string HinhDinhKem { get; set; }
        public string LyDo { get; set; }
    
        public virtual TaiKhoanHeThong TaiKhoanHeThong { get; set; }
        public virtual TaiKhoanHeThong TaiKhoanHeThong1 { get; set; }
    }
}
