//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoSoTuChonBenTre
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int AuthorDetailsID { get; set; }
        public Nullable<int> menu_id { get; set; }
        public Nullable<bool> them { get; set; }
        public Nullable<bool> sua { get; set; }
        public Nullable<bool> xoa { get; set; }
        public Nullable<bool> inan { get; set; }
        public int IDTaiKhoan { get; set; }
    
        public virtual TaiKhoanHeThong TaiKhoanHeThong { get; set; }
    }
}
