//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoSoTuChonBenTre
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraThuong
    {
        public int IDTraThuong { get; set; }
        public int IDNguoiTra { get; set; }
        public Nullable<int> NgayTraThuong { get; set; }
        public Nullable<int> IDPhieuDuThuong { get; set; }
        public string SoPhieu { get; set; }
        public string SoDuThuong { get; set; }
        public string So { get; set; }
        public string Lo { get; set; }
    
        public virtual TaiKhoanHeThong TaiKhoanHeThong { get; set; }
    }
}
